# Generated by Django 5.0.4 on 2024-05-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='peofile_image',
            new_name='profile_image',
        ),
    ]
