# Generated by Django 5.0.6 on 2024-06-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_github',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.JPG', null=True, upload_to='profiles/'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
