# Generated by Django 5.0.6 on 2024-07-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_teammember_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='idn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
