# Generated by Django 5.0.6 on 2024-06-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, default='events/default.JPG', null=True, upload_to='events/'),
        ),
    ]
