# Generated by Django 5.0.6 on 2024-06-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticketprices_price_currency_alter_ticketprices_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprices',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_prices', to='events.event'),
        ),
    ]
