# Generated by Django 5.0.6 on 2024-06-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_ticketprices_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprices',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketprices',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
