# Generated by Django 5.0.6 on 2024-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_ticketprices_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprices',
            name='init_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
