# Generated by Django 5.0.6 on 2024-06-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0006_rename_id_paymenthistory_uuid'),
        ('events', '0015_ticketprices_init_amount'),
        ('users', '0008_remove_profile_social_github_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketPrices',
            new_name='TicketPrice',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='ticketprice',
            old_name='init_amount',
            new_name='initial_amount',
        ),
    ]
