# Generated by Django 5.0.6 on 2024-06-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_rename_ticketprices_ticketprice_rename_id_event_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketprice',
            name='initial_amount',
        ),
    ]
