# Generated by Django 5.0.6 on 2024-06-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_ticketprice_initial_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprice',
            name='initial_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
