# Generated by Django 5.0.6 on 2024-06-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_ticket_id_alter_ticketlevel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='owner',
        ),
    ]
