# Generated by Django 5.0.6 on 2024-06-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_ticket_status'),
        ('users', '0008_remove_profile_social_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='users.profile'),
        ),
    ]
