# Generated by Django 5.0.6 on 2024-06-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_ticket_order_id_ticket_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='owner',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
