# Generated by Django 5.0.6 on 2024-06-17 15:39

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=events.models.qr_code_upload_path),
        ),
    ]
