# Generated by Django 5.0.6 on 2024-06-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_ticket_qr_code'),
        ('users', '0008_remove_profile_social_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlevel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
