# Generated by Django 5.0.6 on 2024-07-03 15:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_ticketlevel_owner'),
        ('users', '0011_alter_teammember_idn'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teammember')),
            ],
        ),
    ]
