# Generated by Django 5.0.6 on 2024-07-03 16:22

import django.db.models.deletion
import events.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_memberpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to=events.models.pass_qr_code_upload_path)),
                ('_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.memberpass')),
            ],
        ),
    ]
