# Generated by Django 5.0.6 on 2024-07-17 21:39

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=events.models.generate_uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
