# Generated by Django 5.0.6 on 2024-06-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
        ('events', '0014_ticketprices_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='ticket_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.ticketprices'),
            preserve_default=False,
        ),
    ]
