# Generated by Django 5.0.6 on 2024-06-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_alter_paymenthistory_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='qr_code',
            field=models.ImageField(blank=True, default=1, upload_to='qr_codes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='total_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
