# Generated by Django 5.0.6 on 2024-06-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0004_alter_paymenthistory_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
