# Generated by Django 5.0.6 on 2024-06-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0005_alter_paymenthistory_qr_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='id',
            new_name='uuid',
        ),
    ]
