# Generated by Django 5.0.6 on 2024-06-11 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0007_rename_uuid_paymenthistory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='UUid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
