# Generated by Django 5.0.6 on 2024-06-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0008_remove_paymenthistory_id_paymenthistory_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='UUid',
            new_name='id',
        ),
    ]
