# Generated by Django 5.0.6 on 2024-06-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0009_rename_uuid_paymenthistory_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
