# Generated by Django 5.0.6 on 2024-06-17 06:10

import checkouts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkouts', '0010_delete_paymenthistory'),
        ('events', '0021_alter_ticket_id_alter_ticketlevel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ticket_quantity', models.PositiveIntegerField(default=1)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('order_id', models.CharField(default=checkouts.models.generate_order_id, max_length=8, unique=True)),
                ('stripe_payment_token', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(blank=True, upload_to='order_qr_codes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ticketlevel')),
            ],
        ),
    ]
