# Generated by Django 5.0.6 on 2024-06-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0011_initial'),
        ('events', '0023_alter_ticket_id_alter_ticketlevel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ticket'),
        ),
    ]
