# Generated by Django 5.0.6 on 2024-06-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0012_alter_order_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
    ]
