# Generated by Django 5.0.6 on 2024-06-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0013_remove_order_qr_code'),
        ('events', '0025_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.ticket'),
        ),
    ]
