# Generated by Django 5.0.6 on 2024-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0018_alter_order_ticket_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket_levels',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
