# Generated by Django 5.0.6 on 2024-06-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0019_order_ticket_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticket_levels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
